name: Build EXE Windows

on: 
  push: # Se lance à chaque fois que tu modifies le code
  workflow_dispatch: # Te permet de le lancer manuellement

jobs:
  build:
    runs-on: windows-latest # GitHub utilise un vrai serveur Windows

    steps:
    - name: Recuperation du code
      uses: actions/checkout@v3

    - name: Installation de Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installation des outils
      run: |
        pip install pyinstaller requests
        # Ajoute ici d'autres bibliothèques si ton script en utilise

    - name: Creation du fichier EXE
      # --onefile crée un seul fichier, --noconsole cache la fenêtre noire
      run: pyinstaller --onefile --noconsole grabber_final.py

    - name: Sauvegarder le resultat
      uses: actions/upload-artifact@v4
      with:
        name: MonOutil_Windows
        path: dist/main.exe
        
